# Generated by Django 3.2.7 on 2022-12-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_title', models.CharField(max_length=200)),
                ('Prod_price', models.IntegerField()),
                ('Prod_img', models.ImageField(upload_to='pics')),
                ('Prod_desc', models.CharField(max_length=300)),
            ],
        ),
    ]
